-- ============================================================================
-- 02_RAW_TABLES.SQL - Domain-specific typed table schemas
-- ============================================================================
USE DATABASE OIL_GAS_TRADING;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW.WELLS (
  WELL_ID VARCHAR(20) NOT NULL, WELL_NAME VARCHAR(200), FIELD VARCHAR(50), REGION VARCHAR(50), WELL_TYPE VARCHAR(30), DEPTH_M FLOAT, STATUS VARCHAR(20), SPUD_DATE DATE, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.PRODUCTION_RUNS (
  RUN_ID VARCHAR(30) NOT NULL, ENTITY_ID VARCHAR(20), RUN_DATE DATE, OUTPUT_QTY FLOAT, UNIT VARCHAR(20), RUNTIME_HOURS FLOAT, DOWNTIME_HOURS FLOAT, EFFICIENCY_PCT FLOAT, COST FLOAT, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.MAINTENANCE_EVENTS (
  EVENT_ID VARCHAR(30) NOT NULL, ENTITY_ID VARCHAR(20), EVENT_DATE TIMESTAMP, EVENT_TYPE VARCHAR(30), DESCRIPTION VARCHAR(500), DURATION_HOURS FLOAT, COST FLOAT, PRIORITY VARCHAR(10), STATUS VARCHAR(20), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.RESERVES (
  RESERVE_ID VARCHAR(30) NOT NULL, WELL_ID VARCHAR(20), ASSESSMENT_DATE DATE, CATEGORY VARCHAR(20), OIL_MMBBL FLOAT, GAS_BCF FLOAT, CONDENSATE_MMBBL FLOAT, CONFIDENCE_PCT FLOAT, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
