-- Generated from generator/demo_specs/aws-malaysia-oil-gas-trading.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-malaysia-oil-gas-trading
-- This is the schema that is actually deployed for MY_OIL_GAS_TRADING.

-- Alerts fire on the bottom tail of Avg Brent
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_AVG_BRENT) AS T
  FROM RAW.PRICE_FEEDS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_AVG_BRENT <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_AVG_BRENT), 2) AS AVG_BRENT,
  ROUND(AVG(f.KPI_TAPIS_PREMIUM), 2) AS AVG_TAPIS_PREMIUM,
  ROUND(AVG(f.KPI_STORAGE_CONTANGO), 2) AS AVG_STORAGE_CONTANGO
FROM RAW.PRICE_FEEDS f
JOIN RAW.MARKET_REPORTS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_AVG_BRENT), 2) AS AVG_BRENT,
  ROUND(AVG(f.KPI_TAPIS_PREMIUM), 2) AS AVG_TAPIS_PREMIUM,
  ROUND(AVG(f.KPI_STORAGE_CONTANGO), 2) AS AVG_STORAGE_CONTANGO
FROM RAW.PRICE_FEEDS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_AVG_BRENT) AS KPI_AVG_BRENT, AVG(KPI_TAPIS_PREMIUM) AS KPI_TAPIS_PREMIUM, AVG(KPI_STORAGE_CONTANGO) AS KPI_STORAGE_CONTANGO FROM RAW.PRICE_FEEDS),
     en AS (SELECT SUM(KPI_TRADING_REVENUE) AS KPI_TRADING_REVENUE, SUM(KPI_CARGO_MOVEMENTS) AS KPI_CARGO_MOVEMENTS, SUM(KPI_OPEN_POSITIONS) AS KPI_OPEN_POSITIONS FROM RAW.MARKET_REPORTS)
  SELECT 1 AS SORT_ORDER, 'Trading Revenue' AS TITLE, KPI_TRADING_REVENUE AS VALUE_NUM, 'RM' || ' ' || TO_VARCHAR(CAST(ROUND(((KPI_TRADING_REVENUE) / 1000000000), 1) AS DECIMAL(38,1))) || 'B' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Avg Brent' AS TITLE, KPI_AVG_BRENT AS VALUE_NUM, '$' || TO_VARCHAR(CAST(ROUND((KPI_AVG_BRENT)) AS DECIMAL(38,0))) || '/bbl' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Cargo Movements' AS TITLE, KPI_CARGO_MOVEMENTS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_CARGO_MOVEMENTS)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Open Positions' AS TITLE, KPI_OPEN_POSITIONS AS VALUE_NUM, 'RM' || ' ' || TO_VARCHAR(CAST(ROUND(((KPI_OPEN_POSITIONS) / 1000000)) AS DECIMAL(38,0))) || 'M' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Tapis Premium' AS TITLE, KPI_TAPIS_PREMIUM AS VALUE_NUM, '+' || '$' || TO_VARCHAR(CAST(ROUND((KPI_TAPIS_PREMIUM), 2) AS DECIMAL(38,2))) || '/bbl' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Storage Contango' AS TITLE, KPI_STORAGE_CONTANGO AS VALUE_NUM, '$' || TO_VARCHAR(CAST(ROUND((KPI_STORAGE_CONTANGO), 2) AS DECIMAL(38,2))) || '/bbl' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
