-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Energy Trading & Risk Management
-- ============================================================================
USE DATABASE OIL_GAS_TRADING;
USE SCHEMA ML;

-- ML.ANOMALY_DETECTION: LIMIT_BREACH_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.LIMIT_BREACH_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.LIMIT_UTILISATION'),
  SERIES_COLNAME => 'DESK_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.LIMIT_BREACH_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.LIMIT_BREACH_MODEL!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.LIMIT_UTILISATION'), SERIES_COLNAME => 'DESK_ID', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'Y'));

-- ML.FORECAST: PRICE_TRAJECTORY_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.PRICE_TRAJECTORY_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.PNL_TIMESERIES'),
  SERIES_COLNAME => 'COMMODITY',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y'
  
);

CREATE OR REPLACE TABLE ML.PRICE_TRAJECTORY_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.PRICE_TRAJECTORY_MODEL!FORECAST(FORECASTING_PERIODS => 14));

