-- ============================================================================
-- 99_RESET.SQL — Reset Energy Trading & Risk Management to clean demo state
-- ============================================================================
USE DATABASE OIL_GAS_TRADING;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_RECALCULATE_VAR SUSPEND;
ALTER TASK IF EXISTS APP.TASK_CHECK_LIMITS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_SEND_BREACH_NOTIFICATIONS SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.POSITION_SUMMARY REFRESH;
ALTER DYNAMIC TABLE CURATED.VAR_CALCULATION REFRESH;
ALTER DYNAMIC TABLE CURATED.LIMIT_UTILISATION REFRESH;
ALTER DYNAMIC TABLE CURATED.PNL_TIMESERIES REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM OIL_GAS_TRADING.RAW.TRADES → 50000
-- SELECT COUNT(*) FROM OIL_GAS_TRADING.RAW.PRICE_FEEDS → 500000
-- SELECT COUNT(*) FROM OIL_GAS_TRADING.CURATED.LIMIT_UTILISATION WHERE UTILISATION_PCT > 0.90 → >=5

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_SEND_BREACH_NOTIFICATIONS RESUME;
ALTER TASK IF EXISTS APP.TASK_CHECK_LIMITS RESUME;
ALTER TASK IF EXISTS APP.TASK_RECALCULATE_VAR RESUME;
